version: '3.8'

services:
  user_service_db:
    image: postgres:15
    container_name: user_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: qwertyui
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  user-service:
    image: user_service:latest
    depends_on:
      - user_service_db
    ports:
      - '5000:5000'
    volumes:
      - ./Config.toml:/app/Config.toml
      - ./logs:/app/logs
      - ./public.crt:/home/ballerina/public.crt
    environment:
      BAL_CONFIG_FILES: /app/Config.toml

volumes:
  pgdata:
